export type { AuthContext, AuthUser } from './types.js'
export { hashPassword, verifyPassword } from './password.js'
export { signJwt, verifyJwt } from './jwt.js'
export { createUser, findUserByEmail, findUserById, getLocalDefaultUser } from './dao.js'
export type { CreateUserInput, UserRecord } from './dao.js'
export { resolveAuthContext } from './middleware.js'
export type { AuthMiddlewareDeps } from './middleware.js'
export { authRoutes } from './routes.js'
export type { AuthRoutesDeps } from './routes.js'
