import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stringify } from 'yaml'
import { buildOpenApiDocument } from '../openapi/registry.js'

// apps/server/src/cli/ -> repo root is four levels up.
const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '../../../..')
const outPath = resolve(repoRoot, 'docs/api/openapi.yaml')

const doc = buildOpenApiDocument()
const yaml = stringify(doc)
const banner = '# GENERATED by `pnpm --filter @argus/server gen:openapi` — do not edit by hand.\n'
writeFileSync(outPath, banner + yaml)
console.log(`Wrote ${outPath} (${yaml.length} bytes)`)
